<a href="https://colab.research.google.com/github/KarolChlasta/Perceptron/blob/master/Task2-Percpetron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# Perceptron - five McCulloch-Pitts neurons with 5 inputs
import numpy as np

def perceptron (mi, weights, inputs):
  # theta - activation function of my neuron
  file = open('/content/perceptron.out', 'w')
    for x in (inputs.dot(weights)-mi):
      if x >= 0:
        print(1)
        file.write('1')
      else:
        print(0)
        file.write('0')
  file.close()

###############
# Build Task 1 Neuron
mi = 2 # test neuron threshold

# neuron.cfg file generation
# generate 10 random weights
weights = np.random.randint(2, size=(10))
print(weights)
np.savetxt('/content/neuron.cfg', weights, header=str(mi), fmt='%0.0f')

# neuron.in file generation
# generate 10 random inputs, each 80 chars long to commemorate'78 VT100
inputs = np.random.randint(2, size=(80, 10))
print(inputs)
np.savetxt('/content/neuron.in', inputs.transpose(), fmt='%0.0f')

print(inputs.dot(weights)-mi)

# theta - activation function of my neuron
file = open('/content/neuron.out', 'w')
for x in (inputs.dot(weights)-mi):
  if x >= 0:
    print(1)
    file.write('1')
  else:
    print(0)
    file.write('0')
file.close()

[ 2 -1  3  5]
[[0 1 0 1]
 [1 1 1 0]
 [0 0 1 1]
 [0 1 0 0]]
[ 0  0  4 -5]
1
1
1
0
[1 0 0 1 0 1 0 0 0 1]
[[1 1 1 1 0 0 0 1 0 1]
 [1 1 0 0 1 0 0 0 0 0]
 [1 0 0 1 0 1 1 1 1 0]
 [1 0 1 1 1 0 0 1 0 1]
 [1 1 0 1 1 1 0 1 0 1]
 [0 0 0 1 1 0 0 0 1 0]
 [1 1 0 0 1 0 0 0 1 1]
 [0 0 1 1 0 1 1 1 0 1]
 [1 1 1 0 1 0 0 0 0 0]
 [0 0 1 0 0 1 0 0 1 1]
 [1 0 0 0 0 0 1 1 1 1]
 [0 0 1 0 1 0 1 1 1 1]
 [0 0 0 1 0 1 0 0 1 0]
 [0 1 1 1 1 1 0 0 1 0]
 [1 1 0 0 0 0 1 0 1 0]
 [0 1 1 1 0 0 0 1 0 1]
 [0 1 1 0 0 0 0 1 1 1]
 [1 0 1 1 0 0 1 0 0 0]
 [1 0 1 1 0 1 1 1 0 1]
 [0 0 0 0 1 0 1 1 0 1]
 [0 0 1 1 0 1 1 1 1 0]
 [0 0 1 1 1 0 0 0 0 0]
 [0 0 0 0 1 1 1 0 1 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 0 1 0 1 1 1 1 0 0]
 [0 1 0 0 0 0 0 1 1 1]
 [1 0 1 1 0 1 1 0 0 0]
 [0 1 0 1 0 0 0 1 1 0]
 [1 0 1 1 0 0 1 1 0 0]
 [0 1 0 1 1 0 0 0 0 1]
 [0 1 1 0 0 1 1 1 0 0]
 [0 0 0 0 1 0 0 1 1 1]
 [1 0 0 1 0 0 0 1 0 0]
 [1 1 0 0 0 0 0 1 1 0]
 [1 1 0 0 0 0 0 0 0 1]
 [1 0 0 1 0 1 1 0 0 0]
 [0 1 0 0 0 0 0 0 0 1]
 [0 1 0 0 1 0 1 1 0 1]
 [0 0 1 1 1 1 0 1 1 0]
