<a href="https://colab.research.google.com/github/KarolChlasta/Perceptron/blob/master/Task1-Neuron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# A single McCulloch-Pitts neuron with 4 inputs
import numpy as np

# Build test neuron first
mi_test = 4 # test neuron threshold
weights_test = np.array( [2, -1, 3, 5], dtype=int)
inputs_test = np.array( [[0, 1, 0, 1],
                    [1, 1, 1, 0],
                    [0, 0, 1, 1],
                    [0, 1, 0, 0]], dtype=int)

print(weights_test)
print(inputs_test)
print(inputs_test.dot(weights_test)-mi_test)

# theta - activation function of my test neuron
for x in (inputs_test.dot(weights_test)-mi_test):
  if x >= 0:
    print(1)
  else:
    print(0)
# test neuron was activated three times

###############
# Task 1 Neuron
mi = 2 # test neuron threshold

# neuron.cfg file generation
# generate 10 random weights
weights = np.random.randint(2, size=(10))
print(weights)
np.savetxt('/content/neuron.cfg', weights, header=str(mi), fmt='%0.0f')

# neuron.in file generation
# generate 10 random inputs, each 80 chars long to commemorate'78 VT100
inputs = np.random.randint(2, size=(80, 10))
print(inputs)
np.savetxt('/content/neuron.in', inputs.transpose(), fmt='%0.0f')

# theta - activation function of my neuron
file = open('/content/neuron.out', 'w')
for x in (inputs.dot(weights)-mi):
  if x >= 0:
    print(1)
    file.write('1')
  else:
    print(0)
    file.write('0')
file.close()

# The above should be defined as function
def neuron (mi, weights, inputs):
  outps = []
  for x in (inputs.dot(weights)-mi):
    if x >= 0:
      outps.append(1)
    else:
      outps.append(0)
  result = np.array(outps)
  return result

# test my neuron function
print(neuron(mi_test, weights_test, inputs_test))
#neuron tested - returns array([1, 1, 1, 0]) hurra


[ 2 -1  3  5]
[[0 1 0 1]
 [1 1 1 0]
 [0 0 1 1]
 [0 1 0 0]]
[ 0  0  4 -5]
1
1
1
0
[1 0 1 1 0 0 0 1 0 1]
[[0 1 1 1 0 1 0 0 1 0]
 [1 0 1 1 0 0 1 0 1 1]
 [0 0 0 1 1 1 1 0 1 0]
 [0 0 1 1 0 0 0 0 1 0]
 [0 0 1 0 1 0 0 0 1 0]
 [0 0 1 1 0 0 1 0 0 1]
 [0 1 1 1 0 0 0 0 0 0]
 [0 0 1 1 0 1 1 0 0 1]
 [1 0 1 0 1 0 0 1 0 1]
 [0 1 1 1 0 1 1 1 1 1]
 [1 0 1 0 0 0 0 1 0 0]
 [0 0 0 1 0 1 0 0 0 0]
 [0 1 0 0 0 0 0 1 1 0]
 [0 1 1 1 0 1 0 0 0 1]
 [0 1 1 0 1 0 0 1 0 1]
 [1 1 0 0 1 0 0 0 0 1]
 [1 1 0 0 0 1 1 1 0 1]
 [1 0 1 0 1 0 0 0 1 1]
 [0 0 0 0 1 0 0 1 1 0]
 [1 0 0 0 0 1 1 1 1 0]
 [0 0 0 1 1 1 1 0 1 0]
 [0 0 1 0 1 1 1 1 0 1]
 [0 1 0 1 1 0 1 1 1 0]
 [0 1 1 0 1 1 0 0 0 1]
 [1 1 1 0 1 0 1 0 1 1]
 [0 0 0 0 0 0 0 1 1 1]
 [1 0 1 0 0 0 1 1 1 1]
 [0 1 0 0 1 0 1 1 0 0]
 [0 0 1 0 0 0 1 0 1 0]
 [1 0 1 1 1 0 0 1 0 1]
 [0 0 1 1 1 1 0 1 1 1]
 [1 0 0 0 0 1 0 1 0 0]
 [1 0 1 1 1 1 1 0 0 0]
 [0 1 1 1 1 0 0 1 0 0]
 [1 1 0 0 1 0 1 1 0 0]
 [1 0 1 1 0 1 1 1 1 0]
 [1 0 1 1 1 1 1 0 1 1]
 [0 0 0 1 1 1 1 1 1 0]
 [0 0 1 0 0 1 1 0 0 0]
