<a href="https://colab.research.google.com/github/KarolChlasta/Perceptron/blob/master/Task3-Multi_Layer_Perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
# Two layer perceptron - five McCulloch-Pitts neurons with 5 inputs feeding into three such neurons.
import numpy as np

# Define my perceptron
def myperceptron (mi, weights, inputs):
  neurocalc = np.subtract(inputs.dot(weights), mi)
  outps = []
  for i in range(len(neurocalc)):
        for j in range(len(neurocalc[i])):
                if(neurocalc[i][j]) >= 0:
                  outps.append(1)
                else:
                  outps.append(0)
  return np.array(outps)

# Task 3 - simulate two layer perceptron

# Simulate first layer first
mi = np.random.randint(4, size=(5), dtype=int) # perceptron thresholds

# perceptron.cfg file generation
# generate 25 random weights
weights = np.random.randint(2, size=(5, 5), dtype=int)
np.savetxt('/content/perceptron.cfg', weights, header=str(mi), fmt='%0.0f')

# perceptron.in file generation
# generate 5 random inputs, each 80 chars long to commemorate'78 VT100
inputs = np.random.randint(2, size=(80, 5), dtype=int)
np.savetxt('/content/perceptron.in', inputs.transpose(), fmt='%0.0f')

# perceptron.out file generation
# calculate 400 outputs and save to file, diplay result
np.savetxt('/content/perceptron.out', myperceptron (mi, weights, inputs), fmt='%0.0f')
print(myperceptron (mi, weights, inputs))

# Simulate the second layer
mi2 = np.random.randint(4, size=(3), dtype=int) # perceptron's second later thresholds
print(mi2)

# perceptron2.cfg file generation
# generate 15 random weights
weights2 = np.random.randint(2, size=(5, 3), dtype=int)
np.savetxt('/content/perceptronL2.cfg', weights, header=str(mi2), fmt='%0.0f')
print(weights2)

# perceptronL2.in file generation, reuse outputs from the first layer
np.savetxt('/content/perceptronL2.in', myperceptron (mi, weights, inputs), fmt='%0.0f')

#convert layer two input to a format consumable by my function
inputsL2 = myperceptron (mi, weights, inputs)
#print(np.reshape(inputsL2, (80, 5)))

# perceptron.out file generation
# calculate 240 outputs and save to file, diplay result
np.savetxt('/content/perceptronL2.out', myperceptron(mi2, weights2, np.reshape(inputsL2, (80,5))), fmt='%0.0f')
print(myperceptron(mi2, weights2, np.reshape(inputsL2, (80,5))))


[1 1 1 1 0 1 1 1 1 0 1 1 1 1 0 0 1 1 1 0 0 0 1 1 0 1 1 1 1 0 1 1 1 1 0 1 1
 1 1 0 0 1 1 1 0 0 1 1 1 0 0 1 1 1 0 0 1 1 1 0 0 1 1 1 0 0 1 1 1 0 1 1 1 1
 0 1 1 1 1 0 0 0 1 1 0 1 1 1 1 0 1 1 1 1 0 0 0 1 1 0 1 1 1 1 0 0 1 1 1 0 0
 0 1 1 0 1 1 1 1 0 0 1 1 1 0 0 1 1 1 0 0 1 1 1 0 0 1 1 1 0 0 1 1 1 0 1 1 1
 1 0 0 1 1 1 0 0 1 1 1 0 1 1 1 1 0 1 1 1 1 0 0 1 1 1 0 0 1 1 1 0 0 1 1 1 0
 1 1 1 1 0 1 1 1 1 0 1 1 1 1 0 0 1 1 1 0 0 1 1 1 0 0 1 1 1 0 1 1 1 1 0 0 1
 1 1 0 1 1 1 1 0 0 0 1 1 0 1 1 1 1 0 1 1 1 1 0 1 1 1 1 0 0 1 1 1 0 1 1 1 1
 0 0 1 1 1 0 0 1 1 1 0 1 1 1 1 0 0 0 1 1 0 1 1 1 1 0 1 1 1 1 0 1 1 1 1 0 1
 1 1 1 0 0 1 1 1 0 1 1 1 1 0 1 1 1 1 0 0 0 1 1 0 0 1 1 1 0 0 0 1 1 0 1 1 1
 1 0 1 1 1 1 0 0 1 1 1 0 0 1 1 1 0 0 0 1 1 0 1 1 1 1 0 0 1 1 1 0 0 1 1 1 0
 1 1 1 1 0 0 1 1 1 0 1 1 1 1 0 0 1 1 1 0 0 1 1 1 0 1 1 1 1 0]
[3 2 3]
[[1 0 0]
 [0 0 1]
 [1 0 0]
 [1 0 0]
 [0 1 0]]
[1 0 0 1 0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 0 0 0 0 0 