<a href="https://colab.research.google.com/github/KarolChlasta/Perceptron/blob/master/Task1-Neuron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [58]:
# A single McCulloch-Pitts neuron with 4 inputs
import numpy as np

mi = 4 # neuron threshold

inputs_test = np.array( [[0, 1, 0, 1],
                    [1, 1, 1, 0],
                    [0, 0, 1, 1],
                    [0, 1, 0, 0]], dtype=int)

weights_test = np.array( [2, -1, 3, 5], dtype=int)
print(inputs_test)
print(inputs_test.dot(weights_test)-mi)

# theta - activation function of my neuron
for x in (inputs_test.dot(weights_test)-mi):
  if x >= 0:
    print(1)
  else:
    print(0)

# neuron was activated three times


# neuron.cfg file generation
# generate 10 random weights
weights = np.random.randint(2, size=(10, 1))
print(weights)
np.savetxt('/content/neuron.cfg', weights, header=str(mi), fmt='%0.0f')

# neuron.in file generation
# generate 10 random inputs, each 80 chars long to commemorate'78 VT100
inputs = np.random.randint(2, size=(10, 80))
print(inputs)
np.savetxt('/content/neuron.in', inputs, fmt='%0.0f')

[[0 1 0 1]
 [1 1 1 0]
 [0 0 1 1]
 [0 1 0 0]]
[ 0  0  4 -5]
1
1
1
0
[[1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]]
[[0 0 1 0 0 1 1 1 1 0 0 0 0 0 0 1 1 0 0 1 0 1 0 0 0 1 1 1 1 1 0 1 0 1 0 0
  1 0 1 0 0 1 0 0 1 1 1 0 1 1 1 0 0 0 1 1 0 1 0 1 1 0 0 1 0 0 1 0 1 0 1 1
  1 1 0 0 1 0 1 0]
 [0 1 1 0 0 1 0 0 0 1 0 1 0 0 1 1 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0
  1 1 0 0 0 1 1 0 0 1 1 1 0 1 1 0 0 0 0 0 1 1 1 0 0 0 1 1 1 1 1 1 1 0 0 0
  1 1 1 1 0 1 1 0]
 [1 1 1 1 0 1 1 0 0 1 1 0 0 0 1 0 1 1 1 1 0 0 1 1 1 0 0 1 0 0 0 1 0 1 1 0
  0 0 0 0 1 1 0 1 0 1 1 0 1 1 1 1 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 0 1 1 1 1
  1 0 0 1 1 1 1 1]
 [1 1 1 1 1 0 0 0 1 0 1 0 1 1 0 0 1 1 1 1 0 0 1 1 1 1 0 1 1 1 1 0 0 1 0 0
  0 1 1 0 0 1 0 1 0 1 0 1 1 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 0 0 0 1 1 0
  1 1 0 0 1 0 0 1]
 [0 1 0 0 0 1 1 0 0 1 1 0 1 0 1 1 0 0 0 1 1 0 0 0 0 1 0 1 0 0 0 1 0 0 1 1
  0 0 1 1 1 0 0 1 0 0 1 1 0 0 0 0 1 1 0 0 0 1 0 1 0 0 1 1 1 1 0 1 0 0 0 1
  0 0 0 0 0 1 0 1]
 [1 1 1 0 1 0 1 1 0 1 0 1 0 0 0 1 0 0 1 0 1 0 1